/**HEADER HERE*/

/***********************************************************************
* THIS FILE IS AUTOGENERATED
***********************************************************************/

#ifndef _HREG_DAT_H_
#define _HREG_DAT_H_

#include "Common.h"
#include "Hreg.h"
#include "Hreg_api.h"

#ifndef TEST
#include "System.h"
#include "Flash.h"
#include "GPIO.h"
#include "Uart.h"
#include "Spi.h"
#include "Interrupts.h"
#include "Buttons.h"
#include "Leds.h"
#include "SwTimer.h"
#include "VirtualEeprom.h"
#endif



//System
#define HREG_SYSTEM_POWER_UP_REASON (&tableHregSystem[0])
#define HREG_SYSTEM_POWER_MODE (&tableHregSystem[1])
#define HREG_SYSTEM_DATE (&tableHregSystem[2])
#define HREG_SYSTEM_TIME (&tableHregSystem[3])


//Flash
#define HREG_FLASH_SIZE (&tableHregFlash[0])
#define HREG_FLASH_DATA (&tableHregFlash[1])
#define HREG_FLASH_OFFSET (&tableHregFlash[2])


//GPIO
#define HREG_GPIO_VALUE (&tableHregGPIO[0])


//Uart
#define HREG_UART_BUFFER_SIZE (&tableHregUart[0])
#define HREG_UART_DATA (&tableHregUart[1])
#define HREG_UART_STATUS (&tableHregUart[2])


//Spi
#define HREG_SPI_BUFFER_SIZE (&tableHregSpi[0])
#define HREG_SPI_DATA (&tableHregSpi[1])
#define HREG_SPI_STATUS (&tableHregSpi[2])


//Interrupts
#define HREG_INTERRUPTS_STATE (&tableHregInterrupts[0])


//Buttons
#define HREG_BUTTONS_STATE (&tableHregButtons[0])


//Leds
#define HREG_LEDS_EFFECT (&tableHregLeds[0])
#define HREG_LEDS_STATE (&tableHregLeds[1])


//SwTimer
#define HREG_SWTIMER_CALLBACK_FUNCTION (&tableHregSwTimer[0])
#define HREG_SWTIMER_GET_PENDING (&tableHregSwTimer[1])
#define HREG_SWTIMER_STATE (&tableHregSwTimer[2])
#define HREG_SWTIMER_GET_ELAPSED (&tableHregSwTimer[3])
#define HREG_SWTIMER_SET (&tableHregSwTimer[4])


//VirtualEEPROM
#define HREG_VIRTUALEEPROM_REGISTER (&tableHregVirtualEEPROM[0])
#define HREG_VIRTUALEEPROM_INSTANCE_REG (&tableHregVirtualEEPROM[1])
#define HREG_VIRTUALEEPROM_DATA (&tableHregVirtualEEPROM[2])


#define NUM_OF_HREGS 26
typedef enum 
{
	 ON_READ_HREG_INDEX_SYSTEM_DATE, 
	 ON_READ_HREG_INDEX_SYSTEM_TIME, 
	 ON_READ_HREG_INDEX_FLASH_SIZE, 
	 ON_READ_HREG_INDEX_FLASH_DATA, 
	 ON_READ_HREG_INDEX_GPIO_VALUE, 
	 ON_READ_HREG_INDEX_UART_BUFFER_SIZE, 
	 ON_READ_HREG_INDEX_UART_DATA, 
	 ON_READ_HREG_INDEX_UART_STATUS, 
	 ON_READ_HREG_INDEX_SPI_BUFFER_SIZE, 
	 ON_READ_HREG_INDEX_SPI_DATA, 
	 ON_READ_HREG_INDEX_SPI_STATUS, 
	 ON_READ_HREG_INDEX_INTERRUPTS_STATE, 
	 ON_READ_HREG_INDEX_BUTTONS_STATE, 
	 ON_READ_HREG_INDEX_LEDS_EFFECT, 
	 ON_READ_HREG_INDEX_LEDS_STATE, 
	 ON_READ_HREG_INDEX_SWTIMER_GET_PENDING, 
	 ON_READ_HREG_INDEX_SWTIMER_STATE, 
	 ON_READ_HREG_INDEX_SWTIMER_GET_ELAPSED, 
	 ON_READ_HREG_INDEX_VIRTUALEEPROM_DATA, 
	 ON_READ_HREG_INDEX_MAX, 
}eOnReadHregIndex;

typedef enum 
{
	 ON_WRITE_HREG_INDEX_SYSTEM_POWER_MODE, 
	 ON_WRITE_HREG_INDEX_SYSTEM_DATE, 
	 ON_WRITE_HREG_INDEX_SYSTEM_TIME, 
	 ON_WRITE_HREG_INDEX_FLASH_DATA, 
	 ON_WRITE_HREG_INDEX_GPIO_VALUE, 
	 ON_WRITE_HREG_INDEX_UART_BUFFER_SIZE, 
	 ON_WRITE_HREG_INDEX_UART_DATA, 
	 ON_WRITE_HREG_INDEX_SPI_BUFFER_SIZE, 
	 ON_WRITE_HREG_INDEX_SPI_DATA, 
	 ON_WRITE_HREG_INDEX_INTERRUPTS_STATE, 
	 ON_WRITE_HREG_INDEX_LEDS_EFFECT, 
	 ON_WRITE_HREG_INDEX_LEDS_STATE, 
	 ON_WRITE_HREG_INDEX_SWTIMER_CALLBACK_FUNCTION, 
	 ON_WRITE_HREG_INDEX_SWTIMER_STATE, 
	 ON_WRITE_HREG_INDEX_SWTIMER_SET, 
	 ON_WRITE_HREG_INDEX_VIRTUALEEPROM_DATA, 
	 ON_WRITE_HREG_INDEX_MAX, 
}eOnWriteHregIndex;

typedef enum 
{
	 HREG_GROUP_INDEX_SYSTEM, 
	 HREG_GROUP_INDEX_FLASH, 
	 HREG_GROUP_INDEX_GPIO, 
	 HREG_GROUP_INDEX_UART, 
	 HREG_GROUP_INDEX_SPI, 
	 HREG_GROUP_INDEX_INTERRUPTS, 
	 HREG_GROUP_INDEX_BUTTONS, 
	 HREG_GROUP_INDEX_LEDS, 
	 HREG_GROUP_INDEX_SWTIMER, 
	 HREG_GROUP_INDEX_VIRTUALEEPROM, 
	 HREG_GROUP_INDEX_MAX, 
}eHregGroupIndex;

extern const HREG_FUNC_READ_CALL onReadHregFunc[19];
extern const HREG_FUNC_WRITE_CALL onWriteHregFunc[16];
extern const HREG_GROUP_INT_CALL apiFuncHregGroup[10];
extern HREG_GROUP_STATE hregGroupsState[10];
extern const HREG tableHregSystem[4];
extern const HREG tableHregFlash[3];
extern const HREG tableHregGPIO[1];
extern const HREG tableHregUart[3];
extern const HREG tableHregSpi[3];
extern const HREG tableHregInterrupts[1];
extern const HREG tableHregButtons[1];
extern const HREG tableHregLeds[2];
extern const HREG tableHregSwTimer[5];
extern const HREG tableHregVirtualEEPROM[3];
extern const HREG_TABLE_INFO hregTableList[10];
extern const HREG_FUNC hregFunc;
#endif
