/***********************************************************************
 * @file     VirtualEEPROM_map.h
 *
 * @brief    VirtualEEPROM mapping.
 *
 * @author   generate by MonGenesis
 *
 * @date
 *
 **********************************************************************/

#ifndef _VIRTUALEEPROM_MAP_H_
#define _VIRTUALEEPROM_MAP_H_

/***********************************************************************
* PUBLIC COMMON INCLUDE
***********************************************************************/
#include "Common.h"

/***********************************************************************
* PUBLIC ARCHITECTURE INCLUDE
***********************************************************************/

/***********************************************************************
* PUBLIC DEFINES
***********************************************************************/
#define SIZE_OF_VIRTUAL_EEPROM_CACHE 80

/* Configuration of eeprom emulation in flash, can be custom */
#define START_PAGE_ADDRESS      0x08080000U /*!< Start address of the 1st page in flash, for EEPROM emulation */
#define CYCLES_NUMBER           1U   /*!< Number of 10Kcycles requested, minimum 1 for 10Kcycles (default),
                                        for instance 10 to reach 100Kcycles. This factor will increase
                                        pages number */
#define GUARD_PAGES_NUMBER      2U   /*!< Number of guard pages avoiding frequent transfers (must be multiple of 2): 0,2,4.. */

/* Configuration of crc calculation for eeprom emulation in flash */
#define CRC_POLYNOMIAL_LENGTH   LL_CRC_POLYLENGTH_16B /* CRC polynomial lenght 16 bits */
#define CRC_POLYNOMIAL_VALUE    0x8005U /* Polynomial to use for CRC calculation */
#define NB_OF_VARIABLES         1000U  /*!< Number of variables to handle in eeprom */

/***********************************************************************
* PUBLIC TYPES
***********************************************************************/

//--START MONTSENY AUTOGENERATED

typedef enum eVirtualEEPROM
{
	EEPROM_HREG,
	EEPROM_SREG_FACTORY,
	EEPROM_SREG_CALIBRATION,
	EEPROM_SREG_USER,
	EEPROM_DATA_OTHER,
	NUM_OF_TABLE_EEPROMS,
}tVirtualEEPROM;


typedef enum eVirtualEEPROMhregs
{
	EEPROM_HREG_MAP,
	EEPROM_NUM_OF_HREG,
}tVirtualEEPROMhregs;


typedef enum eVirtualEEPROMfactorySREGS
{
	EEPROM_SREG_FACTORY_MAP,
	EEPROM_NUM_OF_FACTORY_SREG,
}tVirtualEEPROMfactorySREGS;


typedef enum eVirtualEEPROMcalibrationSREGS
{
	EEPROM_SREG_CALIBRATION_MAP,
	EEPROM_NUM_OF_CALIBRATION_SREG,
}tVirtualEEPROMcalibrationSREGS;


typedef enum eVirtualEEPROMuserSREGS
{
	EEPROM_SREG_USER_MAP,
	EEPROM_NUM_OF_USER_SREG,
}tVirtualEEPROMuserSREGS;


typedef enum eVirtualEEPROMdata
{
	EEPROM_DATA_MAP,
	EEPROM_NUM_OF_DATA,
}tVirtualEEPROMdata;


typedef enum eVirtualEEPROMDevice
{
	VIRTUAL_EEPROM,
	NUM_OF_VIRTUAL_EEPROMS,
}tVirtualEEPROMDevice;

//--END MONTSENY AUTOGENERATED


#endif /* _VIRTUALEEPROM_MAP_H_ */
