/***********************************************************************
 * @file     VirtualEEPROM_map.c
 *
 * @brief    VirtualEEPROM mapping.
 *
 * @author   generate by MonGenesis
 *
 * @date
 *
 **********************************************************************/

#ifndef _VIRTUALEEPROM_MAP_C_
#define _VIRTUALEEPROM_MAP_C_

/***********************************************************************
* ARCHITECTURE INCLUDES
***********************************************************************/
#include "Common.h"
#include "hreg_dat.h"

/***********************************************************************
* PRIVATE INCLUDES
***********************************************************************/
#include "VirtualEEPROM_map.h"
#include "VirtualEEPROM.h"

/***********************************************************************
* PRIVATE DEFINES
***********************************************************************/
#define VIRTUAL_EEPROM_AREA_1 FLASH_EEPROM_1
#define VIRTUAL_EEPROM_AREA_2 FLASH_EEPROM_2
#if (VIRTUAL_EEPROM_AREA_1 != VIRTUAL_EEPROM_AREA_2)
#error "Virtual eeprom areas need to be equal"
#endif

/***********************************************************************
* PRIVATE VARIABLES
***********************************************************************/

//--START MONTSENY AUTOGENERATED

const tVirtualEEPROMAreaMap virtualEEPROMhregMap [EEPROM_NUM_OF_HREG] =
{
	/*EEPROM_HREG_MAP                    */ { UNIQUE_EEPROM_INSTANCE,      EEPROM_SIZE_MAP},
};


const tVirtualEEPROMAreaMap virtualEEPROMsregFactoryMap [EEPROM_NUM_OF_FACTORY_SREG] =
{
	/*EEPROM_SREG_FACTORY_MAP            */ { UNIQUE_EEPROM_INSTANCE,      EEPROM_SIZE_MAP},
};


const tVirtualEEPROMAreaMap virtualEEPROMsregCalibrationMap [EEPROM_NUM_OF_CALIBRATION_SREG] =
{
	/*EEPROM_SREG_CALIBRATION_MAP        */ { UNIQUE_EEPROM_INSTANCE,      EEPROM_SIZE_MAP},
};


const tVirtualEEPROMAreaMap virtualEEPROMsregUserMap [EEPROM_NUM_OF_USER_SREG] =
{
	/*EEPROM_SREG_USER_MAP               */ { UNIQUE_EEPROM_INSTANCE,      EEPROM_SIZE_MAP},
};



const tVirtualEEPROMAreaMap virtualEEPROMdataTableMap[EEPROM_NUM_OF_DATA] =
 {
	 /* EEPROM_DATA_MAP 	             */ { UNIQUE_EEPROM_INSTANCE,	EEPROM_SIZE_MAP  },
};

//--END MONTSENY AUTOGENERATED

const tVirtualEEPROMInstanceMap virtualEEPROMInstanceMap [NUM_OF_TABLE_EEPROMS] =
{
/*	{ OffsetSize for Block, Ptr to Table }  */
	/* EEPROM_HREG               */ {1000,             (tVirtualEEPROMAreaMap*)&virtualEEPROMhregMap},
	/* EEPROM_SREG_FACTORY       */ {1000,            (tVirtualEEPROMAreaMap*)&virtualEEPROMsregFactoryMap},
	/* EEPROM_SREG_SERVICE       */ {1000,            (tVirtualEEPROMAreaMap*)&virtualEEPROMsregCalibrationMap},
	/* EEPROM_SREG_USER          */ {1000,            (tVirtualEEPROMAreaMap*)&virtualEEPROMsregUserMap},
	/* EEPROM_DATA_OTHER         */ {1000,            (tVirtualEEPROMAreaMap*)&virtualEEPROMdataTableMap},
};


const tVirtualEEPROMDeviceMap EEPROMDeviceMap[NUM_OF_VIRTUAL_EEPROMS] =
{
	/* {flashArea1, flashArea2}
	 *  flashArea1 	---> name of area flash
	 *  flashArea2 	---> name of area flash */
	 { VIRTUAL_EEPROM_AREA_1, VIRTUAL_EEPROM_AREA_2 }
 };


#endif /* _VIRTUALEEPROM_MAP_C_ */
