/***********************************************************************
 * @file     VirtualEEPROM_map.h
 * 
 * @brief    VirtualEEPROM mapping.
 * 
 * @author   generate by MonGenesis
 * 
 * @date      
 * 
 **********************************************************************/

#ifndef _VIRTUALEEPROM_MAP_H_
#define _VIRTUALEEPROM_MAP_H_

/***********************************************************************
* PUBLIC COMMON INCLUDE
***********************************************************************/
#include "Common.h"

/***********************************************************************
* PUBLIC ARCHITECTURE INCLUDE
***********************************************************************/

/***********************************************************************
* PUBLIC DEFINES
***********************************************************************/
#define SIZE_OF_VIRTUAL_EEPROM_CACHE 80

/***********************************************************************
* PUBLIC TYPES
***********************************************************************/

//--START MONTSENY AUTOGENERATED 

typedef enum eVirtualEEPROM
{
	EEPROM_HREG,
	EEPROM_SREG_FACTORY,
	EEPROM_SREG_CALIBRATION,
	EEPROM_SREG_USER,
	EEPROM_DATA_OTHER,
	NUM_OF_TABLE_EEPROMS,
}tVirtualEEPROM;


typedef enum eVirtualEEPROMhregs
{
	EEPROM_HREG_MAP,
	EEPROM_NUM_OF_HREG,
}tVirtualEEPROMhregs;


typedef enum eVirtualEEPROMfactorySREGS
{
	EEPROM_SREG_FACTORY_MAP,
	EEPROM_NUM_OF_FACTORY_SREG,
}tVirtualEEPROMfactorySREGS;


typedef enum eVirtualEEPROMcalibrationSREGS
{
	EEPROM_SREG_CALIBRATION_MAP,
	EEPROM_NUM_OF_CALIBRATION_SREG,
}tVirtualEEPROMcalibrationSREGS;


typedef enum eVirtualEEPROMuserSREGS
{
	EEPROM_SREG_USER_MAP,
	EEPROM_NUM_OF_USER_SREG,
}tVirtualEEPROMuserSREGS;


typedef enum eVirtualEEPROMdata
{
	EEPROM_DATA_MAP,
	EEPROM_NUM_OF_DATA,
}tVirtualEEPROMdata;


typedef enum eVirtualEEPROMDevice
{
	VIRTUAL_EEPROM,
	NUM_OF_VIRTUAL_EEPROMS,
}tVirtualEEPROMDevice;

//--END MONTSENY AUTOGENERATED 


#endif /* _VIRTUALEEPROM_MAP_H_ */
