/***********************************************************************
 * @file     VirtualEEPROM_map.c
 * 
 * @brief    VirtualEEPROM mapping.
 * 
 * @author   generate by MonGenesis
 * 
 * @date      
 * 
 **********************************************************************/

#ifndef _VIRTUALEEPROM_MAP_C_
#define _VIRTUALEEPROM_MAP_C_

/***********************************************************************
* ARCHITECTURE INCLUDES
***********************************************************************/
#include "Common.h"
#include "hreg_dat.h"

/***********************************************************************
* PRIVATE INCLUDES
***********************************************************************/
#include "VirtualEEPROM_map.h"
#include "VirtualEEPROM.h"

/***********************************************************************
* PRIVATE DEFINES
***********************************************************************/
#define VIRTUAL_EEPROM_AREA_1 FLASH_EEPROM_1
#define VIRTUAL_EEPROM_AREA_2 FLASH_EEPROM_2
#if (VIRTUAL_EEPROM_AREA_1 != VIRTUAL_EEPROM_AREA_2)
#error "Virtual eeprom areas need to be equal"
#endif

/***********************************************************************
* PRIVATE VARIABLES
***********************************************************************/

//--START MONTSENY AUTOGENERATED 

const tVirtualEEPROMAreaInstMap VirtualEEPROMhregMap [EEPROM_NUM_OF_HREG] =
{
	/*EEPROM_HREG_LENGTH                 */ { UNIQUE_EEPROM_INSTANCE,      EEPROM_SIZE_LENGTH},
	/*EEPROM_HREG_CRC                    */ { UNIQUE_EEPROM_INSTANCE,      EEPROM_SIZE_CRC},
	/*EEPROM_HREG_MAP                    */ { UNIQUE_EEPROM_INSTANCE,      EEPROM_SIZE_MAP},         
};
const tVirtualEEPROMAreaMap VirtualEEPROMsregfactoryMap [EEPROM_NUM_OF_SREG_FACTORY] =
{
	/*EEPROM_SREG_FACTORY_LENGTH         */ { EEPROM_SIZE_LENGTH},
	/*EEPROM_SREG_FACTORY_CRC            */ { EEPROM_SIZE_CRC},
	/*EEPROM_SREG_FACTORY_MAP            */ { EEPROM_SIZE_MAP},
};
const tVirtualEEPROMAreaMap VirtualEEPROMsregcalibrationMap [EEPROM_NUM_OF_SREG_CALIBRATION] =
{
	/*EEPROM_SREG_CALIBRATION_LENGTH     */ { EEPROM_SIZE_LENGTH},
	/*EEPROM_SREG_CALIBRATION_CRC        */ { EEPROM_SIZE_CRC},
	/*EEPROM_SREG_CALIBRATION_MAP        */ { EEPROM_SIZE_MAP},
};
const tVirtualEEPROMAreaMap VirtualEEPROMsreguserMap [EEPROM_NUM_OF_SREG_USER] =
{
	/*EEPROM_SREG_USER_LENGTH            */ { EEPROM_SIZE_LENGTH},
	/*EEPROM_SREG_USER_CRC               */ { EEPROM_SIZE_CRC},
	/*EEPROM_SREG_USER_MAP               */ { EEPROM_SIZE_MAP},
	/*EEPROM_SREG_HW_ID,				 */ {1},
	/*EEPROM_SREG_FW_MAJOR_VERSION,		 */ {1},
	/*EEPROM_SREG_FW_MINOR_VERSION,		 */ {1},
};
const tVirtualEEPROMAreaMap VirtualEEPROMdataMap [EEPROM_NUM_OF_DATA] =
{
	/*EEPROM_DATA_LENGTH                 */ { EEPROM_SIZE_LENGTH},
	/*EEPROM_DATA_CRC                    */ { EEPROM_SIZE_CRC},
	/*EEPROM_DATA_MAP                    */ { EEPROM_SIZE_MAP},
};

const tVirtualEEPROMInstanceMap VirtualEEPROMInstanceMap [NUM_OF_TABLE_EEPROM] =
{
/*	{ OffsetSize for Block,    Area type   ,    Area type    */
	/* EEPROM_HREG               */ {100,   EEPROM_AREA_INST,      {.withInst=(tVirtualEEPROMAreaInstMap *)&VirtualEEPROMhregMap}},
	/* EEPROM_SREG_FACTORY       */ {100,   EEPROM_AREA_NO_INST,   {.noInst=(tVirtualEEPROMAreaMap *)&VirtualEEPROMsregfactoryMap}},
	/* EEPROM_SREG_CALIBRATION   */ {100,   EEPROM_AREA_NO_INST,   {.noInst=(tVirtualEEPROMAreaMap *)&VirtualEEPROMsregcalibrationMap}},
	/* EEPROM_SREG_USER          */ {100,   EEPROM_AREA_NO_INST,   {.noInst=(tVirtualEEPROMAreaMap *)&VirtualEEPROMsreguserMap}},
	/* EEPROM_DATA               */ {3000,  EEPROM_AREA_NO_INST,   {.noInst=(tVirtualEEPROMAreaMap *)&VirtualEEPROMdataMap}},
};


//--END MONTSENY AUTOGENERATED

const tVirtualEEPROMDeviceMap EEPROMDeviceMap[NUM_OF_VIRTUAL_EEPROMS] = 
{
	/* {flashArea1, flashArea2} 
	 *  flashArea1 	---> name of area flash
	 *  flashArea2 	---> name of area flash */ 
	 { VIRTUAL_EEPROM_AREA_1, VIRTUAL_EEPROM_AREA_2 } 
};


#endif /* _VIRTUALEEPROM_MAP_C_ */
