/***********************************************************************
 * @file     VirtualEEPROM_map.h
 * 
 * @brief    VirtualEEPROM mapping.
 * 
 * @author   generate by MonGenesis
 * 
 * @date      
 * 
 **********************************************************************/

#ifndef _VIRTUALEEPROM_MAP_H_
#define _VIRTUALEEPROM_MAP_H_

/***********************************************************************
* PUBLIC COMMON INCLUDE
***********************************************************************/
#include "Common.h"

/***********************************************************************
* PUBLIC ARCHITECTURE INCLUDE
***********************************************************************/

/***********************************************************************
* PUBLIC DEFINES
***********************************************************************/
#define SIZE_OF_VIRTUAL_EEPROM_CACHE 80

/***********************************************************************
* PUBLIC TYPES
***********************************************************************/

//--START MONTSENY AUTOGENERATED 

typedef enum eVirtualEEPROM
{
	EEPROM_HREG,
	EEPROM_SREG_FACTORY,
	EEPROM_SREG_CALIBRATION,
	EEPROM_SREG_USER,
	EEPROM_DATA,
	NUM_OF_TABLE_EEPROM
}tVirtualEEPROM;

typedef enum eVirtualEEPROMhreg
{
	EEPROM_HREG_LENGTH,
	EEPROM_HREG_CRC,
	EEPROM_HREG_MAP,
	EEPROM_NUM_OF_HREG
}tVirtualEEPROMhreg;


typedef enum eVirtualEEPROMsregfactory
{
	EEPROM_SREG_FACTORY_LENGTH,
	EEPROM_SREG_FACTORY_CRC,
	EEPROM_SREG_FACTORY_MAP,
	EEPROM_NUM_OF_SREG_FACTORY
}tVirtualEEPROMsregfactory;


typedef enum eVirtualEEPROMsregcalibration
{
	EEPROM_SREG_CALIBRATION_LENGTH,
	EEPROM_SREG_CALIBRATION_CRC,
	EEPROM_SREG_CALIBRATION_MAP,

	EEPROM_NUM_OF_SREG_CALIBRATION
}tVirtualEEPROMsregcalibration;


typedef enum eVirtualEEPROMsreguser
{
	EEPROM_SREG_USER_LENGTH,
	EEPROM_SREG_USER_CRC,
	EEPROM_SREG_USER_MAP,

	EEPROM_NUM_OF_SREG_USER
}tVirtualEEPROMsreguser;


typedef enum eVirtualEEPROMdata
{
	EEPROM_DATA_LENGTH,
	EEPROM_DATA_CRC,
	EEPROM_DATA_MAP,
	EEPROM_NUM_OF_DATA
}tVirtualEEPROMdata;

//--END MONTSENY AUTOGENERATED

typedef enum eVirtualEEPROMDevice
{
	VIRTUAL_EEPROM,
	NUM_OF_VIRTUAL_EEPROMS,
}tVirtualEEPROMDevice;

#endif /* _VIRTUALEEPROM_MAP_H_ */
